### ISSUE TITLE
Audio sink and source remain after all clients disconnect

### ISSUE THREAD

**Issue by PassiveLemon** [WiVRn/WiVRn#100]
When killing the last client on the server, the audio sink and source remain. https://github.com/WiVRn/WiVRn/issues/54 might play a role in this issue.

I know you added https://github.com/WiVRn/WiVRn/commit/e70c427fe8f57f68287946319f1fd2ab0dbeeaa9 to try to fix this as discussed in Discord, however I tested on the latest commit as of now and that did not resolve it.

**Comment by PassiveLemon** [comment]
I think this is related to forking. When a headset connects, the server (in the systemd service) is forked, presumably for the headset connection as per `--no-forking`. When the last server client is killed, this fork remains, even though the headset is not connected and so the audio devices are not removed.

```
################################################################################
#                                                                              #
#                        The Monado service has started.                       #
#                                                                              #
################################################################################
 INFO [client_loop] Client 1 connected
 INFO [ipc_handle_instance_describe_client] Client info:
	id: 1
	application_name: 'xrgears'
	pid: 1814787
	extensions:
		ext_hand_tracking_enabled: false
		ext_eye_gaze_interaction_enabled: false
		ext_hand_interaction_enabled: false
 WARN [log_frame_time_diff] Frame late by 9.88ms!
 WARN [log_frame_time_diff] Frame late by 17.45ms!
 WARN [log_frame_time_diff] Frame late by 13.04ms!
 WARN [log_frame_time_diff] Frame late by 9.41ms!
 WARN [log_frame_time_diff] Frame late by 6.76ms!
 WARN [log_frame_time_diff] Frame late by 4.83ms!
 WARN [log_frame_time_diff] Frame late by 3.47ms!
 WARN [log_frame_time_diff] Frame late by 0.56ms!
 # Running `kill $(pgrep xrgears)`
 INFO [client_loop] Client disconnected.
 ```
 ```
 $ pgrep wivrn
1814058
1814384
```

`--no-fork` fails to start the Monado service when connecting, but this feels intentional.

**Comment by xytovl** [comment]
With `--no-fork`, the service should start normally, serve one connection in the same process then exit.

In both cases, the monado process should quit when all clients have exited.

**Comment by Dalmaron** [comment]
Same issue, found Wivrn server created on connection was not being killed properly when client disconnected. As requested attached is the stack trace from the second server created during connection.

[gdb.txt](https://github.com/user-attachments/files/18788344/gdb.txt)

**Comment by xytovl** [comment]
Can you test if https://github.com/WiVRn/WiVRn/tree/fix/exit-deadlock behaves differently? It tries to terminate the threads in a different order, possibly avoiding the nvidia deadlock

**Comment by PassiveLemon** [comment]
When killing the last client (wlx-overlay-s) the audio devices are still not removed. It also throws an error.
[wivrn.log](https://github.com/user-attachments/files/18994360/wivrn.log)

**Comment by xytovl** [comment]
Are you able to get more details on the status when this happens? If the child wivrn-server process is still alive, a dump of its threads could be useful. For this you have to run  `gdb -p <pid>` where the pid is the child one, then run `thread apply all bt`.
https://sourceware.org/gdb/current/onlinedocs/gdb.html/Logging-Output.html describes how to log to a file.

**Comment by PassiveLemon** [comment]
I think I got it: [gdb.txt](https://github.com/user-attachments/files/19032364/gdb.txt)

**Comment by xytovl** [comment]
> I think I got it: [gdb.txt](https://github.com/user-attachments/files/19032408/gdb.txt)

It doesn't look like the connection was closed:
> Thread 2 (Thread 0x7f69fcffd6c0 (LWP 3238545) ".wivrn-server-w"):
#0  0x00007f6a9450ba8f in poll () from /nix/store/81mi7m3k3wsiz9rrrg636sx21psj20hc-glibc-2.40-66/lib/libc.so.6
#1  0x000055a269bdf793 in int wivrn::wivrn_connection::poll<wivrn::wivrn_session&>(wivrn::wivrn_session&, int) [clone .isra.0] ()
#2  0x000055a269bdfbb0 in wivrn::wivrn_session::run(std::stop_token) ()
#3  0x000055a269be0df4 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (wivrn::wivrn_session::*)(std::stop_token), wivrn::wivrn_session*, std::stop_token> > >::_M_run() ()
#4  0x00007f6a948ed0a4 in execute_native_thread_routine () from /nix/store/ggqfrwgzpr3v3dkvh4cnmhymnvf6cqja-gcc-14-20241116-lib/lib/libstdc++.so.6
#5  0x00007f6a944968e3 in start_thread () from /nix/store/81mi7m3k3wsiz9rrrg636sx21psj20hc-glibc-2.40-66/lib/libc.so.6
#6  0x00007f6a94519efc in __clone3 () from /nix/store/81mi7m3k3wsiz9rrrg636sx21psj20hc-glibc-2.40-66/lib/libc.so.6

The socket is not returning an error.

**Comment by xytovl** [comment]
Cuda cleanup was missing in nvenc encoders.
https://github.com/WiVRn/WiVRn/tree/fix/nvenc-destroy adds cleanup, does it fix the issue?
https://github.com/WiVRn/WiVRn/tree/fix/exit-deadlock might be necessary in addition to that.

**Comment by xytovl** [comment]
Fixed by a33fae434ef49110dc520c8828072a5ad3e39a3b

**Comment by PassiveLemon** [comment]
Reopening because it seems this issue is present again, as requested by Xytovl

Not sure if this is good but here's a trace [gdb.txt](https://github.com/user-attachments/files/21707605/gdb.txt)

**Comment by ImSapphire** [comment]
Does this still happen on version 26.2 or newer?

**Comment by galister** [comment]
Closing due to no response.

**Comment by KnifeOfDunwall** [comment]
While i havent checked if it was the same reason, audio devices still remain when all headsets are disconnected. they get removed once the app is closed

**Comment by PassiveLemon** [comment]
I believe that is expected from my experience. The audio devices are only removed once all clients (headset and applications) are disconnected
On a different note, is there a way to change that behavior? I would prefer if the audio devices are removed only when the headset disconnects
